name: Continuous Integration
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'update.txt' 
      - '.github/workflows/*'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'update.txt' 
      - '.github/workflows/*'

jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Prepare build directory
        run: mkdir -p _site && chmod 777 _site

      - name: Debug Environment
        run: ls -la

      - name: Build the site in the Jekyll container
        run: |
          export JEKYLL_VERSION=4.0
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          -e JEKYLL_ENV=production \
          -e PAGES_REPO_NWO=${{ github.repository }} \
          jekyll/builder:$JEKYLL_VERSION /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
        working-directory: ${{ github.workspace }}
