name: Write Secrets to env.json

on:
  push:
    branches:
      - master  # atau sesuai dengan branch yang Anda gunakan

jobs:
  write-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Anda bisa menyesuaikan versi Node.js sesuai kebutuhan

      - name: Write secrets to env.json
        run: |
          const fs = require('fs');
          const path = './env.json';

          const secrets = {
            "email": {
              "EMAIL_USER": "${{ secrets.EMAIL_USER }}",
              "EMAIL_USER_PRODUCT": "${{ secrets.EMAIL_USER_PRODUCT }}",
              "EMAIL_PASS": "${{ secrets.EMAIL_PASS }}",
              "EMAIL_PASS_PRODUCT": "${{ secrets.EMAIL_PASS_PRODUCT }}",
              "EMAIL_SECURE": "${{ secrets.EMAIL_SECURE }}",
              "EMAIL_PORT": "${{ secrets.EMAIL_PORT }}",
              "EMAIL_HOST": "${{ secrets.EMAIL_HOST }}"
            },
            "github": {
              "GITHUB_TOKEN": "${{ secrets.GH_TOKEN }}",
              "GITHUB_REPO": "${{ secrets.GH_REPO }}",
              "GITHUB_FILE_PATH": "${{ secrets.GH_FILE_PATH }}",
              "GITHUB_BRANCH": "${{ secrets.GH_BRANCH }}"
            },
            "firebase": {
              "FIREBASE_API_KEY": "${{ secrets.FIREBASE_API_KEY }}",
              "FIREBASE_APP_ID": "${{ secrets.FIREBASE_APP_ID }}",
              "FIREBASE_AUTH_DOMAIN": "${{ secrets.EMAIL_FIREBASE_AUTH_DOMAIN }}",
              "FIREBASE_DATABASE_URL": "${{ secrets.FIREBASE_DATABASE_URL }}",
              "FIREBASE_PROJECT_ID": "${{ secrets.FIREBASE_PROJECT_ID }}",
              "FIREBASE_STORAGE_BUCKET": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
              "FIREBASE_MESSAGING_SENDER_ID": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
              "FIREBASE_PRIVATE_KEY": "${{ secrets.FIREBASE_PRIVATE_KEY }}",
              "FIREBASE_CLIENT_EMAIL": "${{ secrets.FIREBASE_CLIENT_EMAIL }}",
              "FIREBASE_AUTH_URI": "${{ secrets.FIREBASE_AUTH_URI }}",
              "FIREBASE_TOKEN_URI": "${{ secrets.FIREBASE_TOKEN_URI }}",
              "FIREBASE_PRIVATE_KEY_ID": "${{ secrets.FIREBASE_PRIVATE_KEY_ID }}",
              "FIREBASE_CLIENT_ID": "${{ secrets.FIREBASE_CLIENT_ID }}",
              "FIREBASE_AUTH_PROVIDER_X509_CERT_URL": "${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}",
              "FIREBASE_CLIENT_X509_CERT_URL": "${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}",
              "FIREBASE_LASTSENT": "${{ secrets.FIREBASE_LASTSENT }}",
              "FIREBASE_SUBSCRIBER": "${{ secrets.FIREBASE_SUBSCRIBER }}"
            },
            "other": {
              "SERVICE": "${{ secrets.SERVICE }}",
              "SLUG_TO_MAIL": "${{ secrets.SLUG_TO_MAIL }}"
            }
          };

          // Write secrets to env.json file
          fs.writeFileSync(path, JSON.stringify(secrets, null, 2));

      - name: Upload env.json artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-json
          path: ./env.json
