name: Create and Push env.json

on:
  push:
    branches:
      - master  # Ganti dengan branch Anda jika perlu

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate env.json file
        run: |
          echo '{
            "email": {
              "EMAIL_USER": "${{ secrets.EMAIL_USER }}",
              "EMAIL_USER_PRODUCT": "${{ secrets.EMAIL_USER_PRODUCT }}",
              "EMAIL_PASS": "${{ secrets.EMAIL_PASS }}",
              "EMAIL_PASS_PRODUCT": "${{ secrets.EMAIL_PASS_PRODUCT }}",
              "EMAIL_SECURE": "${{ secrets.EMAIL_SECURE }}",
              "EMAIL_PORT": "${{ secrets.EMAIL_PORT }}",
              "EMAIL_HOST": "${{ secrets.EMAIL_HOST }}"
            },
            "github": {
              "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}",
              "GITHUB_REPO": "${{ secrets.GITHUB_REPO }}",
              "GITHUB_FILE_PATH": "${{ secrets.GITHUB_FILE_PATH }}",
              "GITHUB_BRANCH": "${{ secrets.GITHUB_BRANCH }}"
            },
            "firebase": {
              "FIREBASE_API_KEY": "${{ secrets.FIREBASE_API_KEY }}",
              "FIREBASE_APP_ID": "${{ secrets.FIREBASE_APP_ID }}",
              "FIREBASE_AUTH_DOMAIN": "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
              "FIREBASE_DATABASE_URL": "${{ secrets.FIREBASE_DATABASE_URL }}",
              "FIREBASE_PROJECT_ID": "${{ secrets.FIREBASE_PROJECT_ID }}",
              "FIREBASE_STORAGE_BUCKET": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
              "FIREBASE_MESSAGING_SENDER_ID": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
              "FIREBASE_PRIVATE_KEY": "${{ secrets.FIREBASE_PRIVATE_KEY }}",
              "FIREBASE_CLIENT_EMAIL": "${{ secrets.FIREBASE_CLIENT_EMAIL }}",
              "FIREBASE_AUTH_URI": "${{ secrets.FIREBASE_AUTH_URI }}",
              "FIREBASE_TOKEN_URI": "${{ secrets.FIREBASE_TOKEN_URI }}",
              "FIREBASE_PRIVATE_KEY_ID": "${{ secrets.FIREBASE_PRIVATE_KEY_ID }}",
              "FIREBASE_CLIENT_ID": "${{ secrets.FIREBASE_CLIENT_ID }}",
              "FIREBASE_AUTH_PROVIDER_X509_CERT_URL": "${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}",
              "FIREBASE_CLIENT_X509_CERT_URL": "${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}",
              "FIREBASE_LASTSENT": "${{ secrets.FIREBASE_LASTSENT }}",
              "FIREBASE_SUBSCRIBER": "${{ secrets.FIREBASE_SUBSCRIBER }}"
            },
            "other": {
              "SERVICE": "${{ secrets.SERVICE }}",
              "SLUG_TO_MAIL": "${{ secrets.SLUG_TO_MAIL }}"
            }
          }' > env.json

      - name: Add env.json to Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add env.json
          git commit -m "Add generated env.json"
          git push origin ${{ github.ref }}

