name: Scheduled Publish

on:
  schedule:
    - cron: '0 * * * *'  # Jalankan setiap jam

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Publish Scheduled Files
        env:
          TZ: Asia/Makassar  # Mengatur zona waktu ke Asia/Makassar
        run: |
          # Definisikan waktu saat ini
          CURRENT_DATE=$(date +"%Y-%m-%d %H:%M:%S %z")
          echo "Waktu sekarang: $CURRENT_DATE"

          # Fungsi untuk memeriksa dan memindahkan file jika waktu sesuai
          move_file_if_scheduled() {
            local src_file="$1"
            local dest_folder="$2"
            local date_in_file=$(grep "date: '" "$src_file" | awk -F"'" '{print $2}')
            
            # Bandingkan waktu dalam file dengan waktu saat ini
            if [[ "$date_in_file" < "$CURRENT_DATE" ]] || [[ "$date_in_file" == "$CURRENT_DATE" ]]; then
              # Pindahkan file ke folder tujuan
              dest_file=$(echo "$src_file" | sed "s|_drafts|$dest_folder|; s|_draftsamp|$dest_folder|")
              mkdir -p "$(dirname "$dest_file")"
              mv "$src_file" "$dest_file"
              echo "File $src_file dipindahkan ke $dest_file"
            else
              echo "File $src_file dijadwalkan untuk masa mendatang: $date_in_file"
            fi
          }

          # Iterasi file di _drafts dan _draftsamp
          echo "Memeriksa folder _drafts:"
          for file in _drafts/*.md; do
            [ -e "$file" ] || continue
            move_file_if_scheduled "$file" "_artikel"
          done

          echo "Memeriksa folder _draftsamp:"
          for file in _draftsamp/*.md; do
            [ -e "$file" ] || continue
            move_file_if_scheduled "$file" "_amp"
          done

          # Memastikan isi folder tujuan setelah pemindahan
          echo "Isi folder _artikel setelah pemindahan:"
          ls -l _artikel || echo "_artikel folder is empty."

          echo "Isi folder _amp setelah pemindahan:"
          ls -l _amp || echo "_amp folder is empty."

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Cek status git untuk melihat apakah ada perubahan
          git status

          # Jika ada perubahan, lakukan commit dan push
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Publish scheduled articles"
            git push
            echo "Perubahan berhasil dicommit dan dipush."
          else
            echo "Tidak ada perubahan yang perlu dipush."
          fi
