name: Post to Twitter from RSS

on:
  schedule:
    - cron: '0 * * * *' # Menjalankan setiap jam
  workflow_dispatch:

jobs:
  post_twitter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Sesuaikan dengan versi Node.js yang Anda gunakan

      - name: Install dependencies
        run: |
          npm install

      - name: Run server.js to post on Twitter
        run: |
          node app/post-twitter/server.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub Token untuk akses API
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
