name: Publish Scheduled Posts

on: [push, pull_request]

jobs:
  publish_drafts_to_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move drafts to articles
        run: |
          mkdir -p _artikel
          for file in $(find _drafts -type f -name '*.md'); do
            mv "$file" "_artikel/$(basename "$file")"
          done

      - name: Commit and push changes for articles
        run: |
          git config --global user.name 'ajax-jquery'
          git config --global user.email 'fkansaz@gmail.com'
          git remote set-url origin https://ajax-jquery:$GITHUB_TOKEN@github.com/ajax-jquery/sabdaliterasi.shop.git
          git add .
          git commit -m "Published drafts to articles"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_drafts_to_amp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move drafts to AMP
        run: |
          mkdir -p _amp
          for file in $(find _draftsamp -type f -name '*.md'); do
            mv "$file" "_amp/$(basename "$file")"
          done

      - name: Commit and push changes for AMP
        run: |
          git config --global user.name 'ajax-jquery'
          git config --global user.email 'fkansaz@gmail.com'
          git remote set-url origin https://ajax-jquery:$GITHUB_TOKEN@github.com/ajax-jquery/sabdaliterasi.shop.git
          git add .
          git commit -m "Published drafts AMP"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
