name: Scheduled Publish

on:
  schedule:
    - cron: '5 * * * *'
  push:
    paths:
      - 'update.txt'
  workflow_dispatch:

jobs:
  combined_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Publish Scheduled Files
        id: publish_files
        env:
          TZ: Asia/Makassar
        run: |
          CURRENT_DATE=$(date +"%Y-%m-%d %H:%M:%S %z")
          echo -e "\n\033[1;36mWaktu sekarang: $CURRENT_DATE\033[0m\n"
          
          drafts_publish_count=0
          drafts_schedule_count=0
          draftsamp_publish_count=0
          draftsamp_schedule_count=0

          move_file_if_scheduled() {
            local src_file="$1"
            local dest_folder="$2"
            local date_in_file=$(grep "date: '" "$src_file" | awk -F"'" '{print $2}')
            
            if [[ "$date_in_file" < "$CURRENT_DATE" ]] || [[ "$date_in_file" == "$CURRENT_DATE" ]]; then
              if [[ "$dest_folder" == "_artikel" ]]; then
                dest_file=$(echo "$src_file" | sed "s|_drafts/|_artikel/|")
                drafts_publish_count=$((drafts_publish_count + 1))
              elif [[ "$dest_folder" == "_amp" ]]; then
                dest_file=$(echo "$src_file" | sed "s|_draftsamp/|_amp/|")
                draftsamp_publish_count=$((draftsamp_publish_count + 1))
              fi
              mkdir -p "$(dirname "$dest_file")"
              mv "$src_file" "$dest_file"
              echo -e "\033[1;32mFile $src_file dipindahkan ke $dest_file (Terpublish)\033[0m"
            else
              if [[ "$dest_folder" == "_artikel" ]]; then
                drafts_schedule_count=$((drafts_schedule_count + 1))
              elif [[ "$dest_folder" == "_amp" ]]; then
                draftsamp_schedule_count=$((draftsamp_schedule_count + 1))
              fi
              echo -e "\033[1;33mFile $src_file dijadwalkan untuk masa mendatang: $date_in_file\033[0m"
            fi
          }

          echo -e "\033[1;34mMemeriksa folder _drafts:\033[0m"
          for file in _drafts/*.md; do
            [ -e "$file" ] || continue
            move_file_if_scheduled "$file" "_artikel"
          done

          echo -e "\033[1;32mTotal file terpublish di _drafts: $drafts_publish_count\033[0m"
          echo -e "\033[1;33mTotal file terjadwal di masa depan di _drafts: $drafts_schedule_count\033[0m"

          echo -e "\033[1;34mMemeriksa folder _draftsamp:\033[0m"
          for file in _draftsamp/*.md; do
            [ -e "$file" ] || continue
            move_file_if_scheduled "$file" "_amp"
          done

          echo -e "\033[1;32mTotal file terpublish di _draftsamp: $draftsamp_publish_count\033[0m"
          echo -e "\033[1;33mTotal file terjadwal di masa depan di _draftsamp: $draftsamp_schedule_count\033[0m"

          echo -e "\033[1;36mIsi folder _artikel setelah pemindahan:\033[0m"
          ls -l _artikel || echo "_artikel folder is empty."

          echo -e "\033[1;36mIsi folder _amp setelah pemindahan:\033[0m"
          ls -l _amp || echo "_amp folder is empty."

          if (( drafts_publish_count > 0 || draftsamp_publish_count > 0 )); then
            echo "HAS_PUBLISHED_FILES=true" >> $GITHUB_ENV
          else
            echo "HAS_PUBLISHED_FILES=false" >> $GITHUB_ENV
          fi

      - name: Verify Folder Contents Before Upload
        run: |
          echo "Checking _artikel folder contents:"
          ls -la ${{ github.workspace }}/_artikel || echo "_artikel folder not found or empty."
          echo "Checking _amp folder contents:"
          ls -la ${{ github.workspace }}/_amp || echo "_amp folder not found or empty."

      - name: Set Publish Status
        id: set_publish_status
        run: |
          echo "::set-output name=has_published_files::${{ env.HAS_PUBLISHED_FILES }}"

      - name: Commit and Push Changes
        if: env.HAS_PUBLISHED_FILES == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git status
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Publish scheduled articles"
            git push
            echo "Perubahan berhasil dicommit dan dipush."
          else
            echo "Tidak ada perubahan yang perlu dipush."

      - name: Build Jekyll Site
        if: env.HAS_PUBLISHED_FILES == 'true'
        run: |
          export JEKYLL_VERSION=4.0
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          -e PAGES_REPO_NWO=${{ github.repository }} \
          jekyll/builder:$JEKYLL_VERSION /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

      - name: Setup Ruby for Pages
        if: env.HAS_PUBLISHED_FILES == 'true'
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Configure Pages
        id: pages
        if: env.HAS_PUBLISHED_FILES == 'true'
        uses: actions/configure-pages@v4

      - name: Build with Jekyll for Pages
        if: env.HAS_PUBLISHED_FILES == 'true'
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload Pages Artifact
        if: env.HAS_PUBLISHED_FILES == 'true'
        uses: actions/upload-pages-artifact@v2

      - name: Deploy to GitHub Pages
        if: env.HAS_PUBLISHED_FILES == 'true'
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        uses: actions/deploy-pages@v3
